[SERVICE]
    Flush         5
    Daemon        Off
    Log_Level     debug
    Parsers_File  ${FLUENT_BIT_PATH}/parsers.conf

[INPUT]
    Name           tail
    Path           ${LOG_ORIGINALI}/*.log
    Parser         access_log_custom
    Tag            web_logs
    DB             ${FLUENT_BIT_PATH}/Fluent1/tail1.db
    Read_from_Head true

[FILTER]
    Name    grep
    Match   *
    Exclude ip ^(10\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[0-1])\.|127\.0\.0\.1)

[FILTER]
    Name    grep
    Match   web_logs
    Exclude agent (GPTBot|ChatGPT-User|ClaudeBot|Amazonbot|Google-Extended|CCBot|PerplexityBot|meta-externalagent)

[FILTER]
    Name    grep
    Match   *
    Regex   referrer .

[FILTER]
    Name          rewrite_tag
    Match         web_logs
    Rule          $path (\.\.\/|etc\/|union|select|insert|phpinfo|\.env|config|wp-admin|xmlrpc)  alert  true

[FILTER]
    Name    grep
    Match   *
    Exclude log .

[OUTPUT]
    Name          file
    Match         alert
    Path          ${FLUENT_BIT_PATH}/parsed-logs-alert
    File          possible_vulnerability_scan.txt
    Format        plain

[OUTPUT]
    Name   file
    Match  *
    Path   ${FLUENT_BIT_PATH}/parsed-logs
    File   access_logs-complete.txt
    Format plain

[OUTPUT]
    Name            es
    Match           *
    Host            ${HOST}
    Port            ${PORT}
    HTTP_User       ${HTTP_USER}
    HTTP_Passwd     ${HTTP_PASSWORD}
    Index           access_logs-complete
    tls             On
    tls.verify      Off
    Suppress_Type_Name On
    Buffer_Size        5MB