[PARSER]
    Name access_log_custom
    Format regex
    Regex   ^\[(?<time>[^\]]+)\]\s+(?<req_time>[0-9\.]+)\s+(?<host>\S+)\s+(?<ip>\S+)\s+(?<status>\d+)\s+(?<bytes>\d+)\s+"(?<method>\S+)\s+(?<path>[^"]+)\s+(?<protocol>[^"]+)"(?:\s+"(?<referrer>[^"]*)")?(?:\s+"(?<agent>[^"]*)")?


[PARSER]
    Name        parser_access_logs-complete
    Format      regex
    Regex       ^{"time":"(?<data>.\S+)\s+[^ ]*","req_time":"(?<req_time>.*?)","host":"(?<host>.*?)","ip":"(?<ip>.*?)","status":"(?<status>.*?)","bytes":"(?<bytes>.*?)","method":"(?<method>.*?)","path":"(?<path>.*?)","protocol":"(?<protocol>.*?)","referrer":"(?<referrer>.*?)","agent":"(?<agent>.*?)"}$
    Time_Key    data
    Time_Format  %d/%b/%Y:%H:%M:%S
    Time_Keep   On
