[SERVICE]
    Flush         5
    Daemon        Off
    Log_Level     debug
    Parsers_File  ${FLUENT_BIT_PATH}/parsers.conf

[INPUT]
    Name          tail
    Tag           access_logs-complete
    Path          ${FLUENT_BIT_PATH}/parsed-logs/access_logs-complete.txt
    Parser        parser_access_logs-complete
    DB            ${FLUENT_BIT_PATH}/Fluent2/tail2.db
    Read_from_Head true

[FILTER]
    Name    lua
    Match   access_logs-complete
    script  ${FLUENT_BIT_PATH}/Fluent2/csv_access_logs-complete.lua
    call    aggregate

[OUTPUT]
    Name   file
    Match  access_logs-complete
    Path   ${FLUENT_BIT_PATH}
    File   Access_logs-complete.csv
    Format csv
    csv_column_names  false